version: '3.1'

services:
  nginx:
    image: nginx:1.17
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - container-network
    depends_on:
      - flask

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    networks:
      - container-network
    restart: always

networks:
  container-network:
